repository:
  name: find-terraform-modules
  description: GitHub Action to find all Terraform module directories in a monorepo
  default_branch: main
  topics: terraform, github-actions
branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        contexts:
          - test
      restrictions: null
labels:
  - name: dependencies
  - name: automerge
